# Data Cleaning

## Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

## Step 2. Import the dataset

In [2]:
df = pd.read_table("C:/Users/hp/Downloads/chipotle.tsv")
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

## Step 3. Assign it to a variable called chipo.

In [3]:
chipo=pd.read_table("C:/Users/hp/Downloads/chipotle.tsv")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

## Step 4. See the first 10 entries

In [4]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [5]:
# Solution 1

chipo.shape[0]

4622

In [6]:
# Solution 2

chipo.shape

(4622, 5)

### Step 6. What is the number of columns in the dataset?

In [7]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [8]:
print(chipo.columns)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [9]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [10]:
chipo["item_name"].value_counts().idxmax()

'Chicken Bowl'

### Step 10. For the most-ordered item, how many items were ordered?

In [11]:
most_ordered_item = chipo["item_name"].value_counts()
most_ordered_item.max()

726

### Step 11. What was the most ordered item in the choice_description column?

In [12]:
chipo["choice_description"].value_counts().head(1)

choice_description
[Diet Coke]    134
Name: count, dtype: int64

### Step 12. How many items were orderd in total?

In [13]:
chipo["quantity"].sum()

np.int64(4972)

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [14]:
chipo["item_price"].dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [15]:
chipo["item_price"] = chipo["item_price"].str.replace("$","")
chipo["item_price"]

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [16]:
chipo["item_price"] = chipo["item_price"].apply(lambda x:float(x))
chipo["item_price"]

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

#### Step 13.c. Check the item price type

In [17]:
chipo["item_price"].dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [18]:
revenue = chipo["item_price"].sum()
revenue

np.float64(34500.16)

### Step 15. How many orders were made in the period?

In [19]:
number_of_order =chipo.shape[0]  #counts total number of rows/items
number_of_order

4622

In [20]:
number_of_order= chipo["order_id"].nunique() #counts total unique orders  
number_of_order

1834

### Step 16. What is the average revenue amount per order?

In [21]:
# Solution 1
total_revenue =chipo["item_price"].sum()  
total_revenue

np.float64(34500.16)

In [22]:
total_order= chipo["order_id"].nunique() #total unique orders
total_order

1834

In [23]:
# Solution 2
average_revenue_per_order= total_revenue / total_order
average_revenue_per_order

np.float64(18.811428571428575)

### Step 17. How many different items are sold?

In [24]:
num_of_different_items= chipo["item_name"].nunique()
num_of_different_items

50